Update productController.js
remove method is deprecated.

on my insomia, after i input the params and click send, the output is 
	"message": "product.remove is not a function",
	"stack": "TypeError: product.remove is not a function

as per checking in stackoverflow.
document.remove() is deprecated. Replace remove() with deleteOne() or deleteMany(). 

https://stackoverflow.com/questions/75913878/problem-with-user-remove-it-says-that-it-is-not-a-function